import {
  CrowdZone,
  TerminalCrowdState,
  CrowdTimelineSnapshot,
  CrowdAuditEntry,
} from '@/types/crowd';

export const INITIAL_TERMINAL_B_ZONES: CrowdZone[] = [
  {
    id: 'sec-zone-2',
    name: 'Security Checkpoint Zone 2',
    terminalId: 'terminal-b',
    category: 'SECURITY',
    occupancy: 920,
    capacity: 1000,
    densityPercent: 92,
    queueLength: 184,
    estimatedWaitMin: 17,
    incomingFlow: 124,
    outgoingFlow: 92,
    netFlow: 32,
    dwellTimeMin: 14,
    status: 'CRITICAL',
    openLanes: 6,
    totalLanes: 8,
    pressureScore: 84,
    aiInsight:
      'Queue growth (+16% / 10 min) is exceeding outgoing screening throughput. Opening Lane 7 projected to reduce queue by 28 passengers in 8 minutes.',
    position: [-2, 0.4, 1.5],
    dimensions: [14, 0.2, 5],
  },
  {
    id: 'checkin-32',
    name: 'Check-In Island 32 (International)',
    terminalId: 'terminal-b',
    category: 'CHECKIN',
    occupancy: 580,
    capacity: 800,
    densityPercent: 72,
    queueLength: 78,
    estimatedWaitMin: 8,
    incomingFlow: 95,
    outgoingFlow: 82,
    netFlow: 13,
    dwellTimeMin: 9,
    status: 'ATTENTION',
    openLanes: 8,
    totalLanes: 10,
    pressureScore: 68,
    aiInsight:
      'Flight AA-1482 & LH-760 passenger check-in surge active. Queue growth moderate, within SLA buffer (<10 min).',
    position: [-5.5, 0.4, -4.5],
    dimensions: [8, 0.2, 4],
  },
  {
    id: 'checkin-33',
    name: 'Check-In Island 33 (Domestic / Fast Bag Drop)',
    terminalId: 'terminal-b',
    category: 'CHECKIN',
    occupancy: 420,
    capacity: 800,
    densityPercent: 52,
    queueLength: 38,
    estimatedWaitMin: 4,
    incomingFlow: 76,
    outgoingFlow: 74,
    netFlow: 2,
    dwellTimeMin: 6,
    status: 'NORMAL',
    openLanes: 8,
    totalLanes: 10,
    pressureScore: 46,
    aiInsight:
      'Automated self bag-drop kiosks operating at 94% uptime. Flow is balanced.',
    position: [2.5, 0.4, -4.5],
    dimensions: [8, 0.2, 4],
  },
  {
    id: 'special-lane-um',
    name: 'Special Assistance & Priority Lane (UM)',
    terminalId: 'terminal-b',
    category: 'SECURITY',
    occupancy: 45,
    capacity: 100,
    densityPercent: 45,
    queueLength: 6,
    estimatedWaitMin: 3,
    incomingFlow: 12,
    outgoingFlow: 14,
    netFlow: -2,
    dwellTimeMin: 5,
    status: 'NORMAL',
    openLanes: 2,
    totalLanes: 2,
    pressureScore: 32,
    aiInsight: 'Priority lane operating with minimal wait (<3 min).',
    position: [6.5, 0.4, 1.5],
    dimensions: [4, 0.2, 4],
  },
  {
    id: 'concourse-b',
    name: 'Concourse B Retail & Waiting Promenade',
    terminalId: 'terminal-b',
    category: 'CONCOURSE',
    occupancy: 1420,
    capacity: 2200,
    densityPercent: 64,
    queueLength: 0,
    estimatedWaitMin: 0,
    incomingFlow: 110,
    outgoingFlow: 102,
    netFlow: 8,
    dwellTimeMin: 22,
    status: 'NORMAL',
    pressureScore: 54,
    aiInsight:
      'Concourse passenger flow is steady. Minor dwell clustering near duty-free central rotunda.',
    position: [-0.5, 0.4, 7],
    dimensions: [18, 0.2, 5],
  },
  {
    id: 'gate-b14',
    name: 'Gate B14 Boarding Lounge',
    terminalId: 'terminal-b',
    category: 'GATE',
    occupancy: 184,
    capacity: 200,
    densityPercent: 92,
    queueLength: 72,
    estimatedWaitMin: 12,
    incomingFlow: 35,
    outgoingFlow: 15,
    netFlow: 20,
    dwellTimeMin: 18,
    status: 'CRITICAL',
    pressureScore: 78,
    aiInsight:
      'High gate density associated with Flight AA-1482 active boarding. Medical emergency operations coordinated in podium zone.',
    position: [8.5, 0.4, 11],
    dimensions: [6, 0.2, 5],
  },
];

export const INITIAL_TERMINAL_CROWD_STATES: Record<string, TerminalCrowdState> = {
  'terminal-a': {
    terminalId: 'terminal-a',
    terminalName: 'Terminal A (Domestic Core)',
    occupancyPercent: 42,
    totalPax: 1890,
    capacityPax: 4500,
    pressureScore: 38,
    status: 'NORMAL',
    criticalZonesCount: 0,
    zones: [
      {
        id: 'sec-zone-1',
        name: 'Terminal A Security Hall',
        terminalId: 'terminal-a',
        category: 'SECURITY',
        occupancy: 380,
        capacity: 1000,
        densityPercent: 38,
        queueLength: 32,
        estimatedWaitMin: 4,
        incomingFlow: 65,
        outgoingFlow: 70,
        netFlow: -5,
        dwellTimeMin: 6,
        status: 'NORMAL',
        openLanes: 6,
        totalLanes: 8,
        pressureScore: 36,
        aiInsight: 'Throughput optimal across all 6 open inspection lanes.',
        position: [-22, 0.4, 8],
        dimensions: [12, 0.2, 6],
      },
    ],
    activeAlerts: [],
    aiInsight: 'Terminal A passenger distribution is nominal across all concourse zones.',
  },
  'terminal-b': {
    terminalId: 'terminal-b',
    terminalName: 'Terminal B (International Wing)',
    occupancyPercent: 84,
    totalPax: 3780,
    capacityPax: 4500,
    pressureScore: 84,
    status: 'CRITICAL',
    criticalZonesCount: 2,
    zones: INITIAL_TERMINAL_B_ZONES,
    activeAlerts: [
      'HIGH DENSITY: Security Checkpoint Zone 2 at 92% capacity',
      'QUEUE SURGE: Security Zone 2 queue +16% in last 10 minutes',
    ],
    aiInsight:
      'Security Zone 2 is the primary pressure point. Incoming flow (+124/min) exceeds screening rate (-92/min), generating a 184 passenger queue.',
  },
  'terminal-c': {
    terminalId: 'terminal-c',
    terminalName: 'Terminal C (Regional North)',
    occupancyPercent: 51,
    totalPax: 2040,
    capacityPax: 4000,
    pressureScore: 45,
    status: 'NORMAL',
    criticalZonesCount: 0,
    zones: [
      {
        id: 'sec-zone-c',
        name: 'Terminal C Security',
        terminalId: 'terminal-c',
        category: 'SECURITY',
        occupancy: 480,
        capacity: 900,
        densityPercent: 53,
        queueLength: 45,
        estimatedWaitMin: 6,
        incomingFlow: 75,
        outgoingFlow: 72,
        netFlow: 3,
        dwellTimeMin: 7,
        status: 'NORMAL',
        openLanes: 5,
        totalLanes: 6,
        pressureScore: 48,
        aiInsight: 'Regional flow balanced.',
        position: [18, 0.4, 8],
        dimensions: [10, 0.2, 5],
      },
    ],
    activeAlerts: [],
    aiInsight: 'All passenger processing checkpoints operating with under 7 min wait.',
  },
  'terminal-d': {
    terminalId: 'terminal-d',
    terminalName: 'Terminal D (General & Charter)',
    occupancyPercent: 67,
    totalPax: 1675,
    capacityPax: 2500,
    pressureScore: 62,
    status: 'ATTENTION',
    criticalZonesCount: 1,
    zones: [
      {
        id: 'sec-zone-d',
        name: 'Terminal D Screening Gate',
        terminalId: 'terminal-d',
        category: 'SECURITY',
        occupancy: 420,
        capacity: 600,
        densityPercent: 70,
        queueLength: 62,
        estimatedWaitMin: 9,
        incomingFlow: 54,
        outgoingFlow: 46,
        netFlow: 8,
        dwellTimeMin: 8,
        status: 'ATTENTION',
        openLanes: 3,
        totalLanes: 4,
        pressureScore: 64,
        aiInsight: 'Charter flight wave generating temporary queue spike.',
        position: [36, 0.4, 14],
        dimensions: [8, 0.2, 4],
      },
    ],
    activeAlerts: ['QUEUE GROWTH: Terminal D screening queue approaching 10 min SLA threshold.'],
    aiInsight: 'Charter flight wave generating temporary queue growth; monitor over next 15 min.',
  },
};

export const CROWD_TIMELINE_SNAPSHOTS: CrowdTimelineSnapshot[] = [
  {
    timeLabel: '08:00',
    timestamp: '2026-09-26T08:00:00Z',
    pressureScore: 32,
    status: 'NORMAL',
    terminals: {
      'terminal-a': { occupancyPercent: 28, pressureScore: 24, status: 'NORMAL' },
      'terminal-b': { occupancyPercent: 38, pressureScore: 32, status: 'NORMAL' },
      'terminal-c': { occupancyPercent: 31, pressureScore: 28, status: 'NORMAL' },
      'terminal-d': { occupancyPercent: 22, pressureScore: 18, status: 'NORMAL' },
    },
    securityQueue: 24,
    securityWaitMin: 3,
  },
  {
    timeLabel: '09:00',
    timestamp: '2026-09-26T09:00:00Z',
    pressureScore: 48,
    status: 'NORMAL',
    terminals: {
      'terminal-a': { occupancyPercent: 36, pressureScore: 34, status: 'NORMAL' },
      'terminal-b': { occupancyPercent: 54, pressureScore: 48, status: 'NORMAL' },
      'terminal-c': { occupancyPercent: 42, pressureScore: 38, status: 'NORMAL' },
      'terminal-d': { occupancyPercent: 35, pressureScore: 30, status: 'NORMAL' },
    },
    securityQueue: 58,
    securityWaitMin: 6,
  },
  {
    timeLabel: '10:00',
    timestamp: '2026-09-26T10:00:00Z',
    pressureScore: 64,
    status: 'ATTENTION',
    terminals: {
      'terminal-a': { occupancyPercent: 40, pressureScore: 38, status: 'NORMAL' },
      'terminal-b': { occupancyPercent: 68, pressureScore: 64, status: 'ATTENTION' },
      'terminal-c': { occupancyPercent: 48, pressureScore: 42, status: 'NORMAL' },
      'terminal-d': { occupancyPercent: 52, pressureScore: 48, status: 'NORMAL' },
    },
    securityQueue: 96,
    securityWaitMin: 9,
  },
  {
    timeLabel: '11:00',
    timestamp: '2026-09-26T11:00:00Z',
    pressureScore: 76,
    status: 'ATTENTION',
    terminals: {
      'terminal-a': { occupancyPercent: 44, pressureScore: 40, status: 'NORMAL' },
      'terminal-b': { occupancyPercent: 78, pressureScore: 76, status: 'ATTENTION' },
      'terminal-c': { occupancyPercent: 52, pressureScore: 46, status: 'NORMAL' },
      'terminal-d': { occupancyPercent: 61, pressureScore: 56, status: 'ATTENTION' },
    },
    securityQueue: 142,
    securityWaitMin: 13,
  },
  {
    timeLabel: '12:00',
    timestamp: '2026-09-26T12:00:00Z',
    pressureScore: 84,
    status: 'CRITICAL',
    terminals: {
      'terminal-a': { occupancyPercent: 42, pressureScore: 38, status: 'NORMAL' },
      'terminal-b': { occupancyPercent: 84, pressureScore: 84, status: 'CRITICAL' },
      'terminal-c': { occupancyPercent: 51, pressureScore: 45, status: 'NORMAL' },
      'terminal-d': { occupancyPercent: 67, pressureScore: 62, status: 'ATTENTION' },
    },
    securityQueue: 184,
    securityWaitMin: 17,
  },
  {
    timeLabel: '13:00 (LIVE)',
    timestamp: '2026-09-26T13:00:00Z',
    pressureScore: 84,
    status: 'CRITICAL',
    terminals: {
      'terminal-a': { occupancyPercent: 42, pressureScore: 38, status: 'NORMAL' },
      'terminal-b': { occupancyPercent: 84, pressureScore: 84, status: 'CRITICAL' },
      'terminal-c': { occupancyPercent: 51, pressureScore: 45, status: 'NORMAL' },
      'terminal-d': { occupancyPercent: 67, pressureScore: 62, status: 'ATTENTION' },
    },
    securityQueue: 184,
    securityWaitMin: 17,
  },
];

export const INITIAL_CROWD_AUDIT_LOG: CrowdAuditEntry[] = [
  {
    id: 'cad-1',
    time: '12:15',
    action: 'Routine Concourse Flow Sweep Completed',
    zoneName: 'Concourse B',
    actor: 'SYSTEM',
    result: 'Flow velocity 1.2 m/s nominal across central spine.',
    pressureBefore: 56,
    pressureAfter: 54,
  },
  {
    id: 'cad-2',
    time: '12:28',
    action: 'Automated Queue Threshold Alert Raised',
    zoneName: 'Security Checkpoint Zone 2',
    actor: 'TWINOS TELEMETRY',
    result: 'Queue passed 150 pax threshold (+14% ingress surge).',
    pressureBefore: 78,
    pressureAfter: 84,
  },
];

/**
 * Calculates a deterministic, explainable Operational Crowd Pressure Index (0-100)
 */
export function calculateCrowdPressureScore(zone: CrowdZone): {
  score: number;
  breakdown: {
    occupancyContrib: number;
    queueContrib: number;
    flowContrib: number;
    dwellContrib: number;
    capacityContrib: number;
  };
} {
  const occRatio = Math.min(1, zone.occupancy / Math.max(1, zone.capacity));
  const occupancyContrib = Math.round(occRatio * 30);
  const queueContrib = Math.round(Math.min(30, (zone.queueLength / 200) * 30));
  const flowDiff = Math.max(0, zone.incomingFlow - zone.outgoingFlow);
  const flowContrib = Math.round(Math.min(20, (flowDiff / 40) * 20));
  const dwellContrib = Math.round(Math.min(10, (zone.dwellTimeMin / 20) * 10));
  const capacityContrib = Math.round(occRatio > 0.85 ? 10 : occRatio > 0.7 ? 5 : 0);

  const score = Math.min(100, occupancyContrib + queueContrib + flowContrib + dwellContrib + capacityContrib);

  return {
    score,
    breakdown: {
      occupancyContrib,
      queueContrib,
      flowContrib,
      dwellContrib,
      capacityContrib,
    },
  };
}
