import {
  CrowdZone,
  TerminalCrowdState,
  CrowdTimelineSnapshot,
  CrowdAuditEntry,
} from '@/types/crowd';

export const INITIAL_TERMINAL_B_ZONES: CrowdZone[] = [
  {
    id: 'sec-zone-2',
    name: 'Security Checkpoint Zone 2',
    terminalId: 'terminal-b',
    category: 'SECURITY',
    occupancy: 920,
    capacity: 1000,
    densityPercent: 92,
    queueLength: 184,
    estimatedWaitMin: 17,
    incomingFlow: 124,
    outgoingFlow: 92,
    netFlow: 32,
    dwellTimeMin: 14,
    status: 'CRITICAL',
    openLanes: 6,
    totalLanes: 8,
    pressureScore: 84,
    aiInsight:
      'Queue growth (+16% / 10 min) is exceeding outgoing screening throughput. Opening Lane 7 projected to reduce queue by 28 passengers in 8 minutes.',
    position: [-2, 0.4, 1.5],
    dimensions: [14, 0.2, 5],
  },
  {
    id: 'checkin-32',
    name: 'Check-In Island 32 (International)',
    terminalId: 'terminal-b',
    category: 'CHECKIN',
    occupancy: 580,
    capacity: 800,
    densityPercent: 72,
    queueLength: 78,
    estimatedWaitMin: 8,
    incomingFlow: 95,
    outgoingFlow: 82,
    netFlow: 13,
    dwellTimeMin: 9,
    status: 'ATTENTION',
    openLanes: 8,
    totalLanes: 10,
    pressureScore: 68,
    aiInsight:
      'Flight AA-1482 & LH-760 passenger check-in surge active. Queue growth moderate, within SLA buffer (<10 min).',
    position: [-5.5, 0.4, -4.5],
    dimensions: [8, 0.2, 4],
  },
  {
    id: 'checkin-33',
    name: 'Check-In Island 33 (Domestic / Fast Bag Drop)',
    terminalId: 'terminal-b',
    category: 'CHECKIN',
    occupancy: 420,
    capacity: 800,
    densityPercent: 52,
    queueLength: 38,
    estimatedWaitMin: 4,
    incomingFlow: 76,
    outgoingFlow: 74,
    netFlow: 2,
    dwellTimeMin: 6,
    status: 'NORMAL',
    openLanes: 8,
    totalLanes: 10,
    pressureScore: 46,
    aiInsight:
      'Automated self bag-drop kiosks operating at 94% uptime. Flow is balanced.',
    position: [2.5, 0.4, -4.5],
    dimensions: [8, 0.2, 4],
  },
  {
    id: 'special-lane-um',
    name: 'Special Assistance & Priority Lane (UM)',
    terminalId: 'terminal-b',
    category: 'SECURITY',
    occupancy: 45,
    capacity: 100,
    densityPercent: 45,
    queueLength: 6,
    estimatedWaitMin: 3,
    incomingFlow: 12,
    outgoingFlow: 14,
    netFlow: -2,
    dwellTimeMin: 5,
    status: 'NORMAL',
    openLanes: 2,
    totalLanes: 2,
    pressureScore: 32,
    aiInsight: 'Priority lane operating with minimal wait (<3 min).',
    position: [6.5, 0.4, 1.5],
    dimensions: [4, 0.2, 4],
  },
  {
    id: 'concourse-b',
    name: 'Concourse B Retail & Waiting Promenade',
    terminalId: 'terminal-b',
    category: 'CONCOURSE',
    occupancy: 1420,
    capacity: 2200,
    densityPercent: 64,
    queueLength: 0,
    estimatedWaitMin: 0,
    incomingFlow: 110,
    outgoingFlow: 102,
    netFlow: 8,
    dwellTimeMin: 22,
    status: 'NORMAL',
    pressureScore: 54,
    aiInsight:
      'Concourse passenger flow is steady. Minor dwell clustering near duty-free central rotunda.',
    position: [-0.5, 0.4, 7],
    dimensions: [18, 0.2, 5],
  },
  {
    id: 'gate-b14',
    name: 'Gate B14 Boarding Lounge',
    terminalId: 'terminal-b',
    category: 'GATE',
    occupancy: 184,
    capacity: 200,
    densityPercent: 92,
    queueLength: 72,
    estimatedWaitMin: 12,
    incomingFlow: 35,
    outgoingFlow: 15,
    netFlow: 20,
    dwellTimeMin: 18,
    status: 'CRITICAL',
    pressureScore: 78,
    aiInsight:
      'High gate density associated with Flight AA-1482 active boarding. Medical emergency operations coordinated in podium zone.',
    position: [8.5, 0.4, 11],
    dimensions: [6, 0.2, 5],
  },
];

export const INITIAL_TERMINAL_A_ZONES: CrowdZone[] = [
  {
    id: 'checkin-a',
    name: 'Check-In Hall A (Domestic Desks 01-16)',
    terminalId: 'terminal-a',
    category: 'CHECKIN',
    occupancy: 420,
    capacity: 900,
    densityPercent: 47,
    queueLength: 28,
    estimatedWaitMin: 4,
    incomingFlow: 72,
    outgoingFlow: 75,
    netFlow: -3,
    dwellTimeMin: 6,
    status: 'NORMAL',
    openLanes: 10,
    totalLanes: 12,
    pressureScore: 36,
    aiInsight: 'Self-service baggage drop operating smoothly. Check-in queue SLA fully satisfied (<5 min).',
    position: [-22, 0.4, 4],
    dimensions: [8, 0.2, 4],
  },
  {
    id: 'sec-zone-a',
    name: 'Terminal A Central Security Hall',
    terminalId: 'terminal-a',
    category: 'SECURITY',
    occupancy: 380,
    capacity: 1000,
    densityPercent: 38,
    queueLength: 32,
    estimatedWaitMin: 4,
    incomingFlow: 68,
    outgoingFlow: 72,
    netFlow: -4,
    dwellTimeMin: 5,
    status: 'NORMAL',
    openLanes: 6,
    totalLanes: 8,
    pressureScore: 32,
    aiInsight: 'Throughput optimal across all 6 open inspection lanes. Queue moving steadily.',
    position: [-22, 0.4, 8],
    dimensions: [12, 0.2, 5],
  },
  {
    id: 'concourse-a',
    name: 'Concourse A Departure Spine & Lounge',
    terminalId: 'terminal-a',
    category: 'CONCOURSE',
    occupancy: 980,
    capacity: 2200,
    densityPercent: 45,
    queueLength: 0,
    estimatedWaitMin: 0,
    incomingFlow: 70,
    outgoingFlow: 68,
    netFlow: 2,
    dwellTimeMin: 18,
    status: 'NORMAL',
    pressureScore: 38,
    aiInsight: 'Domestic concourse passenger velocity nominal (1.3 m/s). Food court seating well distributed.',
    position: [-22, 0.4, 12],
    dimensions: [14, 0.2, 5],
  },
  {
    id: 'gate-a2',
    name: 'Gate A2 Boarding Area (Flight AI-204)',
    terminalId: 'terminal-a',
    category: 'GATE',
    occupancy: 110,
    capacity: 220,
    densityPercent: 50,
    queueLength: 22,
    estimatedWaitMin: 5,
    incomingFlow: 24,
    outgoingFlow: 20,
    netFlow: 4,
    dwellTimeMin: 12,
    status: 'NORMAL',
    pressureScore: 42,
    aiInsight: 'Flight AI-204 boarding readiness nominal. Jetbridge operational.',
    position: [-20.5, 0.4, -8],
    dimensions: [6, 0.2, 4],
  },
];

export const INITIAL_TERMINAL_C_ZONES: CrowdZone[] = [
  {
    id: 'checkin-c',
    name: 'Check-In Hall C (Regional Desks 01-10)',
    terminalId: 'terminal-c',
    category: 'CHECKIN',
    occupancy: 410,
    capacity: 750,
    densityPercent: 55,
    queueLength: 34,
    estimatedWaitMin: 5,
    incomingFlow: 76,
    outgoingFlow: 74,
    netFlow: 2,
    dwellTimeMin: 7,
    status: 'NORMAL',
    openLanes: 6,
    totalLanes: 8,
    pressureScore: 48,
    aiInsight: 'Regional carrier check-in counters operating with standard processing times.',
    position: [18, 0.4, 4],
    dimensions: [8, 0.2, 4],
  },
  {
    id: 'sec-zone-c1',
    name: 'Security Checkpoint C-West (Underutilized)',
    terminalId: 'terminal-c',
    category: 'SECURITY',
    occupancy: 280,
    capacity: 700,
    densityPercent: 40,
    queueLength: 16,
    estimatedWaitMin: 3,
    incomingFlow: 42,
    outgoingFlow: 65,
    netFlow: -23,
    dwellTimeMin: 4,
    status: 'NORMAL',
    openLanes: 4,
    totalLanes: 6,
    pressureScore: 32,
    aiInsight: 'Surplus screening capacity available. Ideal receiver for passenger redirection from Checkpoint C-East.',
    position: [14, 0.4, 8],
    dimensions: [6, 0.2, 4],
  },
  {
    id: 'sec-zone-c2',
    name: 'Security Checkpoint C-East (Overloaded Bottleneck)',
    terminalId: 'terminal-c',
    category: 'SECURITY',
    occupancy: 680,
    capacity: 700,
    densityPercent: 97,
    queueLength: 88,
    estimatedWaitMin: 15,
    incomingFlow: 96,
    outgoingFlow: 68,
    netFlow: 28,
    dwellTimeMin: 12,
    status: 'CRITICAL',
    openLanes: 4,
    totalLanes: 4,
    pressureScore: 88,
    aiInsight: 'Severe queue buildup (+28/m net flow). AI Recommendation: Redirect 25% passenger flow to Checkpoint C-West.',
    position: [22, 0.4, 8],
    dimensions: [6, 0.2, 4],
  },
  {
    id: 'concourse-c',
    name: 'Concourse C Retail Promenade',
    terminalId: 'terminal-c',
    category: 'CONCOURSE',
    occupancy: 860,
    capacity: 1800,
    densityPercent: 48,
    queueLength: 0,
    estimatedWaitMin: 0,
    incomingFlow: 68,
    outgoingFlow: 64,
    netFlow: 4,
    dwellTimeMin: 16,
    status: 'NORMAL',
    pressureScore: 42,
    aiInsight: 'Concourse walking flow steady; cafe and seating areas balanced.',
    position: [18, 0.4, 12],
    dimensions: [12, 0.2, 5],
  },
  {
    id: 'gate-c3',
    name: 'Gate C3 Boarding Gate (Flight LH-760)',
    terminalId: 'terminal-c',
    category: 'GATE',
    occupancy: 130,
    capacity: 200,
    densityPercent: 65,
    queueLength: 26,
    estimatedWaitMin: 6,
    incomingFlow: 25,
    outgoingFlow: 18,
    netFlow: 7,
    dwellTimeMin: 14,
    status: 'NORMAL',
    pressureScore: 52,
    aiInsight: 'Boarding call initiated for LH-760. Flow through jetbridge smooth.',
    position: [16, 0.4, -6],
    dimensions: [6, 0.2, 4],
  },
];

export const INITIAL_TERMINAL_D_ZONES: CrowdZone[] = [
  {
    id: 'checkin-d',
    name: 'Terminal D Charter Check-In',
    terminalId: 'terminal-d',
    category: 'CHECKIN',
    occupancy: 340,
    capacity: 600,
    densityPercent: 57,
    queueLength: 32,
    estimatedWaitMin: 5,
    incomingFlow: 48,
    outgoingFlow: 45,
    netFlow: 3,
    dwellTimeMin: 6,
    status: 'NORMAL',
    openLanes: 4,
    totalLanes: 6,
    pressureScore: 48,
    aiInsight: 'Charter tour group processing smoothly through bulk counters.',
    position: [36, 0.4, 10],
    dimensions: [7, 0.2, 4],
  },
  {
    id: 'sec-zone-d',
    name: 'Terminal D Screening Gate',
    terminalId: 'terminal-d',
    category: 'SECURITY',
    occupancy: 460,
    capacity: 650,
    densityPercent: 71,
    queueLength: 58,
    estimatedWaitMin: 9,
    incomingFlow: 56,
    outgoingFlow: 48,
    netFlow: 8,
    dwellTimeMin: 8,
    status: 'ATTENTION',
    openLanes: 3,
    totalLanes: 4,
    pressureScore: 66,
    aiInsight: 'Charter departure wave generating temporary queue growth; wait approaching 10 min SLA threshold.',
    position: [36, 0.4, 14],
    dimensions: [8, 0.2, 4],
  },
  {
    id: 'concourse-d',
    name: 'Terminal D Departure Lounge',
    terminalId: 'terminal-d',
    category: 'CONCOURSE',
    occupancy: 620,
    capacity: 1100,
    densityPercent: 56,
    queueLength: 0,
    estimatedWaitMin: 0,
    incomingFlow: 44,
    outgoingFlow: 40,
    netFlow: 4,
    dwellTimeMin: 15,
    status: 'NORMAL',
    pressureScore: 46,
    aiInsight: 'Lounge seating occupancy at 56%. Airflow and lighting nominal.',
    position: [36, 0.4, 18],
    dimensions: [9, 0.2, 5],
  },
  {
    id: 'gate-d2',
    name: 'Gate D2 Regional Gate (Flight SG-214)',
    terminalId: 'terminal-d',
    category: 'GATE',
    occupancy: 95,
    capacity: 150,
    densityPercent: 63,
    queueLength: 18,
    estimatedWaitMin: 4,
    incomingFlow: 18,
    outgoingFlow: 14,
    netFlow: 4,
    dwellTimeMin: 10,
    status: 'NORMAL',
    pressureScore: 48,
    aiInsight: 'Pre-flight passenger staging for SG-214 on schedule.',
    position: [34, 0.4, 6],
    dimensions: [5, 0.2, 4],
  },
];

export const INITIAL_TERMINAL_CROWD_STATES: Record<string, TerminalCrowdState> = {
  'terminal-a': {
    terminalId: 'terminal-a',
    terminalName: 'Terminal A (Domestic Core)',
    occupancyPercent: 42,
    totalPax: 1890,
    capacityPax: 4500,
    pressureScore: 38,
    status: 'NORMAL',
    criticalZonesCount: 0,
    zones: INITIAL_TERMINAL_A_ZONES,
    activeAlerts: [],
    aiInsight: 'Terminal A passenger distribution is nominal across all concourse zones. Security wait under 4 minutes.',
  },
  'terminal-b': {
    terminalId: 'terminal-b',
    terminalName: 'Terminal B (International Wing)',
    occupancyPercent: 84,
    totalPax: 3780,
    capacityPax: 4500,
    pressureScore: 84,
    status: 'CRITICAL',
    criticalZonesCount: 2,
    zones: INITIAL_TERMINAL_B_ZONES,
    activeAlerts: [
      'HIGH DENSITY: Security Checkpoint Zone 2 at 92% capacity',
      'QUEUE SURGE: Security Zone 2 queue +16% in last 10 minutes',
    ],
    aiInsight:
      'Security Zone 2 is the primary pressure point. Incoming flow (+124/min) exceeds screening rate (-92/min), generating a 184 passenger queue. Recommend opening 2 screening lanes.',
  },
  'terminal-c': {
    terminalId: 'terminal-c',
    terminalName: 'Terminal C (Regional North)',
    occupancyPercent: 62,
    totalPax: 2480,
    capacityPax: 4000,
    pressureScore: 68,
    status: 'ATTENTION',
    criticalZonesCount: 1,
    zones: INITIAL_TERMINAL_C_ZONES,
    activeAlerts: [
      'CHECKPOINT IMBALANCE: Checkpoint C-East queue (88 pax) exceeds Checkpoint C-West (16 pax)',
    ],
    aiInsight:
      'Significant queue disparity between screening zones. Checkpoint C-East is congested (+28/m net flow) while C-West has spare capacity. Recommend diverting 25% flow to C-West.',
  },
  'terminal-d': {
    terminalId: 'terminal-d',
    terminalName: 'Terminal D (General & Charter)',
    occupancyPercent: 67,
    totalPax: 1675,
    capacityPax: 2500,
    pressureScore: 62,
    status: 'ATTENTION',
    criticalZonesCount: 1,
    zones: INITIAL_TERMINAL_D_ZONES,
    activeAlerts: ['QUEUE GROWTH: Terminal D screening queue approaching 10 min SLA threshold.'],
    aiInsight: 'Charter flight wave generating temporary queue growth; monitor over next 15 min.',
  },
};

export const CROWD_TIMELINE_SNAPSHOTS: CrowdTimelineSnapshot[] = [
  {
    timeLabel: '08:00',
    timestamp: '2026-09-26T08:00:00Z',
    pressureScore: 32,
    status: 'NORMAL',
    terminals: {
      'terminal-a': { occupancyPercent: 28, pressureScore: 24, status: 'NORMAL' },
      'terminal-b': { occupancyPercent: 38, pressureScore: 32, status: 'NORMAL' },
      'terminal-c': { occupancyPercent: 31, pressureScore: 28, status: 'NORMAL' },
      'terminal-d': { occupancyPercent: 22, pressureScore: 18, status: 'NORMAL' },
    },
    securityQueue: 24,
    securityWaitMin: 3,
  },
  {
    timeLabel: '09:00',
    timestamp: '2026-09-26T09:00:00Z',
    pressureScore: 48,
    status: 'NORMAL',
    terminals: {
      'terminal-a': { occupancyPercent: 36, pressureScore: 34, status: 'NORMAL' },
      'terminal-b': { occupancyPercent: 54, pressureScore: 48, status: 'NORMAL' },
      'terminal-c': { occupancyPercent: 42, pressureScore: 38, status: 'NORMAL' },
      'terminal-d': { occupancyPercent: 35, pressureScore: 30, status: 'NORMAL' },
    },
    securityQueue: 58,
    securityWaitMin: 6,
  },
  {
    timeLabel: '10:00',
    timestamp: '2026-09-26T10:00:00Z',
    pressureScore: 64,
    status: 'ATTENTION',
    terminals: {
      'terminal-a': { occupancyPercent: 40, pressureScore: 38, status: 'NORMAL' },
      'terminal-b': { occupancyPercent: 68, pressureScore: 64, status: 'ATTENTION' },
      'terminal-c': { occupancyPercent: 48, pressureScore: 42, status: 'NORMAL' },
      'terminal-d': { occupancyPercent: 52, pressureScore: 48, status: 'NORMAL' },
    },
    securityQueue: 96,
    securityWaitMin: 9,
  },
  {
    timeLabel: '11:00',
    timestamp: '2026-09-26T11:00:00Z',
    pressureScore: 76,
    status: 'ATTENTION',
    terminals: {
      'terminal-a': { occupancyPercent: 44, pressureScore: 40, status: 'NORMAL' },
      'terminal-b': { occupancyPercent: 78, pressureScore: 76, status: 'ATTENTION' },
      'terminal-c': { occupancyPercent: 52, pressureScore: 46, status: 'NORMAL' },
      'terminal-d': { occupancyPercent: 61, pressureScore: 56, status: 'ATTENTION' },
    },
    securityQueue: 142,
    securityWaitMin: 13,
  },
  {
    timeLabel: '12:00',
    timestamp: '2026-09-26T12:00:00Z',
    pressureScore: 84,
    status: 'CRITICAL',
    terminals: {
      'terminal-a': { occupancyPercent: 42, pressureScore: 38, status: 'NORMAL' },
      'terminal-b': { occupancyPercent: 84, pressureScore: 84, status: 'CRITICAL' },
      'terminal-c': { occupancyPercent: 51, pressureScore: 45, status: 'NORMAL' },
      'terminal-d': { occupancyPercent: 67, pressureScore: 62, status: 'ATTENTION' },
    },
    securityQueue: 184,
    securityWaitMin: 17,
  },
  {
    timeLabel: '13:00 (LIVE)',
    timestamp: '2026-09-26T13:00:00Z',
    pressureScore: 84,
    status: 'CRITICAL',
    terminals: {
      'terminal-a': { occupancyPercent: 42, pressureScore: 38, status: 'NORMAL' },
      'terminal-b': { occupancyPercent: 84, pressureScore: 84, status: 'CRITICAL' },
      'terminal-c': { occupancyPercent: 51, pressureScore: 45, status: 'NORMAL' },
      'terminal-d': { occupancyPercent: 67, pressureScore: 62, status: 'ATTENTION' },
    },
    securityQueue: 184,
    securityWaitMin: 17,
  },
];

export const INITIAL_CROWD_AUDIT_LOG: CrowdAuditEntry[] = [
  {
    id: 'cad-1',
    time: '12:15',
    action: 'Routine Concourse Flow Sweep Completed',
    zoneName: 'Concourse B',
    actor: 'SYSTEM',
    result: 'Flow velocity 1.2 m/s nominal across central spine.',
    pressureBefore: 56,
    pressureAfter: 54,
  },
  {
    id: 'cad-2',
    time: '12:28',
    action: 'Automated Queue Threshold Alert Raised',
    zoneName: 'Security Checkpoint Zone 2',
    actor: 'TWINOS TELEMETRY',
    result: 'Queue passed 150 pax threshold (+14% ingress surge).',
    pressureBefore: 78,
    pressureAfter: 84,
  },
];

/**
 * Calculates a deterministic, explainable Operational Crowd Pressure Index (0-100)
 * Weighted Breakdown:
 * - Density: 35%
 * - Queue Depth: 30%
 * - Net Flow Rate: 25%
 * - Wait Time: 10%
 */
export function calculateCrowdPressureScore(zone: CrowdZone): {
  score: number;
  breakdown: {
    densityContrib: number;
    queueContrib: number;
    netFlowContrib: number;
    waitContrib: number;
    formula: string;
  };
} {
  const occRatio = Math.min(1.2, zone.occupancy / Math.max(1, zone.capacity));
  const densityContrib = Math.round(Math.min(35, occRatio * 35));
  const queueContrib = Math.round(Math.min(30, (zone.queueLength / 180) * 30));
  const netFlowPositive = Math.max(0, zone.incomingFlow - zone.outgoingFlow);
  const netFlowContrib = Math.round(Math.min(25, (netFlowPositive / 32) * 25));
  const waitContrib = Math.round(Math.min(10, (zone.estimatedWaitMin / 15) * 10));

  const score = Math.min(100, densityContrib + queueContrib + netFlowContrib + waitContrib);

  return {
    score,
    breakdown: {
      densityContrib,
      queueContrib,
      netFlowContrib,
      waitContrib,
      formula: 'Pressure = Density (35%) + Queue (30%) + Net Flow (25%) + Wait Time (10%)',
    },
  };
}
